# Generated by Django 4.2 on 2025-11-15 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_alter_user_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'کاربر عادی'), ('admin', 'مدیر'), ('staff', 'کارمند'), ('auditor', 'ممیزی')], default='user', max_length=20, verbose_name='نقش کاربر'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('auth_success', 'احراز هویت موفق'), ('auth_failed', 'احراز هویت ناموفق'), ('auth_logout', 'خروج از سیستم'), ('user_create', 'ایجاد کاربر'), ('user_update', 'به\u200cروزرسانی کاربر'), ('user_delete', 'حذف کاربر'), ('user_activate', 'فعال\u200cسازی کاربر'), ('user_deactivate', 'غیرفعال\u200cسازی کاربر'), ('transaction_create', 'ایجاد تراکنش'), ('transaction_update', 'به\u200cروزرسانی تراکنش'), ('wallet_create', 'ایجاد کیف پول'), ('wallet_update', 'به\u200cروزرسانی کیف پول'), ('wallet_suspend', 'تعلیق کیف پول'), ('wallet_activate', 'فعال\u200cسازی کیف پول'), ('config_change', 'تغییر پیکربندی'), ('security_event', 'رویداد امنیتی'), ('access_denied', 'دسترسی رد شد'), ('data_export', 'خروج اطلاعات'), ('admin_action', 'اقدام مدیریتی'), ('system_error', 'خطای سیستم'), ('session_start', 'شروع نشست'), ('session_end', 'پایان نشست'), ('password_change', 'تغییر رمز عبور'), ('permission_change', 'تغییر دسترسی'), ('other', 'سایر')], max_length=50, verbose_name='نوع رویداد')),
                ('event_description', models.TextField(verbose_name='توضیحات رویداد')),
                ('result', models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق'), ('pending', 'در انتظار'), ('cancelled', 'لغو شده')], default='success', max_length=20, verbose_name='نتیجه')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کاربری')),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن کاربر')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='روش درخواست')),
                ('request_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='مسیر درخواست')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='شناسه درخواست')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('integrity_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Hash صحت')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ و زمان')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ امنیتی',
                'verbose_name_plural': 'لاگ\u200cهای امنیتی',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at', 'event_type'], name='audit_logs_created_7fea1d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='audit_logs_user_id_6193b2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', '-created_at'], name='audit_logs_ip_addr_190b84_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type', 'result'], name='audit_logs_event_t_c23826_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['request_id'], name='audit_logs_request_298ea7_idx'),
        ),
    ]
