# Generated by Django 4.2 on 2025-11-07 05:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی')),
                ('currency', models.CharField(default='IRR', max_length=3, verbose_name='ارز')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('suspended', 'تعلیق شده'), ('closed', 'بسته شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('total_transfer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مجموع مبلغ انتقال')),
                ('transfer_count', models.IntegerField(default=0, verbose_name='تعداد انتقال')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'محدودیت کیف پول',
                'verbose_name_plural': 'محدودیت\u200cهای کیف پول',
                'db_table': 'wallet_limits',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True, verbose_name='شناسه تراکنش')),
                ('type', models.CharField(choices=[('charge', 'شارژ'), ('debit', 'برداشت'), ('transfer_in', 'دریافت انتقال'), ('transfer_out', 'ارسال انتقال'), ('refund', 'بازگشت وجه')], max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='موجودی قبل')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='موجودی بعد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه مرجع')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='روش پرداخت')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('recipient_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='wallet.wallet', verbose_name='کیف پول دریافت\u200cکننده')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='wallet.transaction', verbose_name='تراکنش مرتبط')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='walletlimit',
            index=models.Index(fields=['wallet', 'date'], name='wallet_limi_wallet__473636_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='walletlimit',
            unique_together={('wallet', 'date')},
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallets_user_id_9fb6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['status'], name='wallets_status_5720bd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', '-created_at'], name='transaction_wallet__efd4a5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='transaction_transac_5011c8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_505a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='transaction_type_840495_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'),
        ),
    ]
