# Generated by Django 4.2 on 2025-11-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_paymentrequest_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_payload', models.CharField(max_length=64, unique=True, verbose_name='شناسه QR')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='مبلغ ثابت')),
                ('currency', models.CharField(default='IRR', max_length=3, verbose_name='ارز')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('used', 'استفاده شده'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('usage_metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات استفاده')),
            ],
            options={
                'verbose_name': 'QR پرداخت',
                'verbose_name_plural': 'QR های پرداخت',
                'db_table': 'wallet_qr_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_transfe_4f07aa_idx',
            old_name='transaction_transfer__d40fe0_idx',
        ),
        migrations.AddField(
            model_name='walletqrcode',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='wallet.wallet', verbose_name='کیف پول صادرکننده'),
        ),
        migrations.AddIndex(
            model_name='walletqrcode',
            index=models.Index(fields=['qr_payload'], name='wallet_qr_c_qr_payl_d4bfd6_idx'),
        ),
        migrations.AddIndex(
            model_name='walletqrcode',
            index=models.Index(fields=['wallet', 'status'], name='wallet_qr_c_wallet__05a358_idx'),
        ),
        migrations.AddIndex(
            model_name='walletqrcode',
            index=models.Index(fields=['expires_at'], name='wallet_qr_c_expires_62df9c_idx'),
        ),
    ]
