# Generated by Django 4.2 on 2025-11-15 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0006_add_wallet_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='شناسه لینک')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ درخواستی')),
                ('currency', models.CharField(default='IRR', max_length=3, verbose_name='ارز')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('used', 'استفاده شده'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('usage_metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات استفاده')),
            ],
            options={
                'verbose_name': 'لینک پرداخت',
                'verbose_name_plural': 'لینک\u200cهای پرداخت',
                'db_table': 'payment_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='کد اختصاصی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'کد اختصاصی',
                'verbose_name_plural': 'کدهای اختصاصی',
                'db_table': 'special_codes',
            },
        ),
        migrations.RemoveIndex(
            model_name='wallet',
            name='wallets_wallet__idx',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_method',
            field=models.CharField(blank=True, choices=[('phone', 'انتقال با شماره موبایل'), ('contact', 'انتقال به مخاطب ذخیره\u200cشده'), ('wallet_address', 'انتقال به آدرس کیف پول (24 رقمی)'), ('qr', 'انتقال با QR Code'), ('special_code', 'انتقال با کد اختصاصی'), ('link', 'انتقال با لینک پرداخت'), ('nfc', 'انتقال با NFC')], max_length=30, null=True, verbose_name='روش انتقال'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True, unique=True, verbose_name='آدرس کیف پول (24 رقمی)'),
        ),
        migrations.AddField(
            model_name='specialcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_code', to=settings.AUTH_USER_MODEL, verbose_name='کاربر (راننده)'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='used_by_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_payment_links', to='wallet.wallet', verbose_name='کیف پول استفاده\u200cکننده'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='wallet.wallet', verbose_name='کیف پول صادرکننده'),
        ),
        migrations.AddIndex(
            model_name='specialcode',
            index=models.Index(fields=['code'], name='special_cod_code_a84952_idx'),
        ),
        migrations.AddIndex(
            model_name='specialcode',
            index=models.Index(fields=['user', 'is_active'], name='special_cod_user_id_f9fdad_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['link_id'], name='payment_lin_link_id_333fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['wallet', 'status'], name='payment_lin_wallet__d30bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['expires_at'], name='payment_lin_expires_372371_idx'),
        ),
    ]
