# Generated by Django 4.2 on 2025-11-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_paymentlink_specialcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='شناسه درخواست'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['ip_address', '-created_at'], name='transaction_ip_addr_1f87d9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['request_id'], name='transaction_request_eaabc0_idx'),
        ),
    ]
